### PR TITLE
feat(list): add list feature

### PR DESCRIPTION
**Pull request by NoorHasanAlsayed**
BREAKING CHANGE: mailgun library replaced with official nodejs library

Replaced [unofficial mailgun package](https://github.com/mailgun/mailgun-js-boland) with [official one](https://github.com/mailgun/mailgun-js) and added list feature into the code.

### CODE REVIEW

**Comment by NoorHasanAlsayed** [comment]
PS: Forgot to bump the version up a major since it's a breaking change.

**Comment by NextNC** [comment]
@NoorHasanAlsayed Thank you for your contribution! I will review it as soon as possible! 👍

**Comment by NextNC** [comment]
@NoorHasanAlsayed Sorry for the delay I will review it this weekend

**Comment by NoorHasanAlsayed** [comment]
sorry for the late response, I'm so glad you find my work is good.I updated
the readme file

**Comment by NoorHasanAlsayed** [comment]
Thanks 😍😍

**Pull request merged**
